services:
  postgres:
    hostname: postgres
    image: ankane/pgvector
    ports:
     - 5428:5432
    restart: no
    networks:
      - mrag-net
    environment:
      - POSTGRES_DB=vector-database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
     - ./init.sql:/docker-entrypoint-initdb.d/init.sql
     #- /data/zyk/mrag:/var/lib/postgresql/data 
     - /disk2/zyk/MRAG/data/scene_graphs:/var/lib/postgresql/data


networks:
  mrag-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.104.0/25
